#kubectl get -n kube-system configmap aws-auth -o yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397962979:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-gam0fPQKMQ7E
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::767397962979:user/Leela
      username: Leela
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-26T17:55:47Z"
  name: aws-auth
  namespace: kube-system
  uid: 8d7bab8b-2183-4122-abce-9fae9ab17f8e #don't delete this